package gui;

import java.awt.Shape;
import java.util.Set;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import model.*;

/**
 *
 * @author tadaki
 */
public class FractalMain extends javax.swing.JFrame {

    private Fractal sys; 
    /**
     * Creates new form FractalMain
     */
    public FractalMain() {
        initComponents();
        JLabel label = new JLabel("Fractal");
        label.setFont(new java.awt.Font("MS UI Gothic", 0, 14));
        menuBar.add(label);
        JComboBox<FractalFactory.FractalName> fractalList = new JComboBox<>();
        for(FractalFactory.FractalName f:FractalFactory.FractalName.values()){
            fractalList.addItem(f);
        }
        //Action invoked at selecting item in fractalList
        fractalList.addActionListener(l->{
            FractalFactory.FractalName fName= (FractalFactory.FractalName)fractalList.getSelectedItem();
            sys = FractalFactory.createInstance(fName);
        }
        );
        menuBar.add(fractalList);
        sys = FractalFactory.createInstance(FractalFactory.FractalName.Sierpinski);
        fractalList.setSelectedIndex(0);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawPanel = new gui.DrawPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quit = new javax.swing.JMenuItem();
        actionMenu = new javax.swing.JMenu();
        showMap = new javax.swing.JMenuItem();
        oneStep = new javax.swing.JMenuItem();
        fractalInitialize = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawPanel.setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(drawPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        quit.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        fileMenu.add(quit);

        menuBar.add(fileMenu);

        actionMenu.setText("Action");
        actionMenu.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        showMap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        showMap.setText("showMap");
        showMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMapActionPerformed(evt);
            }
        });
        actionMenu.add(showMap);

        oneStep.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, 0));
        oneStep.setText("oneStep");
        oneStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneStepActionPerformed(evt);
            }
        });
        actionMenu.add(oneStep);

        fractalInitialize.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, 0));
        fractalInitialize.setText("initialize");
        fractalInitialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractalInitializeActionPerformed(evt);
            }
        });
        actionMenu.add(fractalInitialize);

        menuBar.add(actionMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        this.dispose();
    }//GEN-LAST:event_quitActionPerformed

    private void showMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMapActionPerformed
        Set<Shape> shapes = sys.getMap();
        drawPanel.draw(shapes,true);
    }//GEN-LAST:event_showMapActionPerformed

    private void oneStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneStepActionPerformed
        Set<Shape> shapes = sys.transform();
        drawPanel.draw(shapes,false);
    }//GEN-LAST:event_oneStepActionPerformed

    private void fractalInitializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractalInitializeActionPerformed
        sys.initialize();
        Set<Shape> shapes = sys.transform();
        drawPanel.draw(shapes,false);
    }//GEN-LAST:event_fractalInitializeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FractalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FractalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FractalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FractalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FractalMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionMenu;
    private gui.DrawPanel drawPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fractalInitialize;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem oneStep;
    private javax.swing.JMenuItem quit;
    private javax.swing.JMenuItem showMap;
    // End of variables declaration//GEN-END:variables
}
